name: to_png
description: Transform your Flutter assets seamlessly with to_png, a powerful package that converts SVG and PDF files into high-quality PNG images.
version: 0.0.1-pre.4
repository: https://github.com/hadysata/to_png/
homepage: https://github.com/hadysata/to_png/

environment:
  sdk: ^3.3.4

dependencies:
  args: ^2.4.2
  image: ^4.1.7
  pdfium_bindings: ^2.0.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
